#! Copyright 2021 VMware, Inc.
#! SPDX-License-Identifier: Apache-2.0

apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: config/release
    contents:
      - path: .
        githubRelease:
          slug: pivotal/kpack
          tag: v0.5.1
          assetNames: ["release-*.yaml"]
  - path: test
    contents:
    - path: .
      git:
        url: https://github.com/pivotal/kpack
        refSelection:
          semver:
            constraints: "0.5.1"
      newRootPath: test